### ISSUE TITLE
Improvement with modern Swift API

### ISSUE THREAD

**Issue by vadimux** [FezZHD/iOS_Playgrounds#1]
https://github.com/FezZHD/iOS_Playgrounds/blob/7f7cd7a7628c5ee408128c3d8675e7cfe0bd67c7/base_playgrounds.playground.playground/Sources/MinMaxArray.swift#L4

as an improvement we can use Swift feature `where` like this:

```
public func minimum<T: Comparable>(_ comparableArray: [T]) -> T {
    var minimalValue = comparableArray[0]
    
    for item in comparableArray where item < minimalValue {
        minimalValue = item
    }
    
    return minimalValue
}
```

**Comment by fezzhd** [comment]
using when with commit a5fdc46c10eae458a93e02647f36bdcf1616f6b1
